import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import SessionProviderWrapper from '../components/sessionProviderWrapper';
import Nav from '@/components/nav';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <SessionProviderWrapper>
         <html lang="en">
            <body className={inter.className}>
               <Nav />
               <div className="container mx-auto px-5 rounded-lg py-8 ring-1 ring-slate-100/5 shadow-xl">{children}</div>
               <Footer />
            </body>
         </html>
      </SessionProviderWrapper>
   );
}
