import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import SessionProviderWrapper from '../components/sessionProviderWrapper';
import AuthStatus from '@/components/authStatus';
import Nav from '@/components/nav';
import DarkSwitch from '@/components/darkSwitch';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <SessionProviderWrapper>
         <html lang="en">
            <body className={inter.className}>
               <Nav />
               <div>{children}</div>
               <hr />
            </body>
         </html>
      </SessionProviderWrapper>
   );
}
