import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import SessionProviderWrapper from '../components/sessionProviderWrapper';
import AuthStatus from '@/components/authStatus';
import Nav from '@/components/nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <SessionProviderWrapper>
         <html lang="en">
            <body className={inter.className}>
               <div className="flex flex-row">
                  <div className="w-4/5 p-3 h-screen bg-black">{children}</div>
                  <div className="w-1/5 p-3 h-screen bg-gray-700">
                     <h2 className="text-3xl">Demo - frontEnd</h2>
                     <AuthStatus />
                     <hr />
                     <Nav />
                  </div>
               </div>
            </body>
         </html>
      </SessionProviderWrapper>
   );
}
